### ISSUE TITLE
Nie działa pobieranie meteogramu ani komentarza synoptyka

### ISSUE THREAD

**Issue by pshemek** [kamil-szostakowski/icmmeteo#38]
**Describe the bug**
Nie działa pobieranie meteogramu ani komentarza synoptyka.

**To Reproduce**
1. Otwórz aplikację.
2. Kliknij dowolne miasto lub zakładkę "Komentarz".
3. Wyświetla się komunikat o niemożliwości pobrania.

**Expected behavior**
Powinien wyświetlać się aktualny meteogram lub komentarz.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.7.2
 - App version: 1.8

**Additional context**
Aktualizacja systemu do 15.7.2 przeprowadzona niedawno.

**Comment by adrian-afl** [comment]
Dokładnie to samo, iOS 16.1.2 na iPhone 11

**Comment by pshemek** [comment]
OK, wersja 1.9 jest w App Store i jak dla mnie naprawia bug.
